### ISSUE TITLE
As a student I need to know the code format

### ISSUE THREAD

**Issue by mykewlker** [MisfitDevs/redistricting#13]
# User Story
### Essential components
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a student
I want to know the code style used
so that the code I add follows suit

## Acceptance Criteria
Rules or scenarios are acceptable formats.

* Defining what format submitted code should be in
* Notifying students of style
* A guideline including style and rules

**Scenario 1**
Given the current code styles or rules of the project
before it is to be turned in
would greatly increase code readability overall 

## Supporting Information
Java by Comparison
The Pragmatic Programmer

**Comment by snoopyvia** [comment]
Refer to issue #14 "[UserStory] Documentation for list of stakeholder"
