### ISSUE TITLE
Working on TO DO in code

### ISSUE THREAD

**Issue by zmorlan1** [MisfitDevs/redistricting#4]
# User Story
### Essential components
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a  coder
I want  work done on TO DO's in code
so that  the code runs more efficiently

## Acceptance Criteria
Rules or scenarios are acceptable formats.

-  In the redistricting on github there are still TO DO's in the code

**Scenario 1**
Given work is done on the TO DO's
when  the TO DO's are completed
then the code will run more effeciently

**Comment by snoopyvia** [comment]
unrelevant
