### ISSUE TITLE
[UserStory] brief identification of the user story

### ISSUE THREAD

**Issue by FrederickBuker** [MisfitDevs/redistricting#5]
# User Story
### Essential components
- [ ] Stakeholder type is identified
- [ ] Outcome is described
- [ ] Rationale is explicit
- [ ] Acceptance criteria are verifiable and from the perspective of the stakeholder

## Story
As a  _stakeholder_
I want  _add up members on both parties and make fair but not overwhelming districts for each party_
so that  _both parties are represented and not left out_

## Acceptance Criteria
Rules or scenarios are acceptable formats.

* _There has to be at least one district won for both parties_
* _No favoritism_
* _A district can have all same members from the same party_

**Scenario 1**
Given  _if one party has more representation then make sure the other party has at least one district_
when  _the high represented party is across the boad it is easy to blow out the other party_
then  _the other party voices might not be heard_

## Supporting Information

**Comment by snoopyvia** [comment]
Refer to issue #14 "[UserStory] Documentation for list of stakeholder"
